/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "background": "#0e0e0e",
        "inverse-primary": "#516700",
        "on-primary-fixed": "#3a4a00",
        "surface-container-low": "#131313",
        "surface-variant": "#262626",
        "primary-container": "#cafd00",
        "on-error-container": "#ffd2c8",
        "secondary-fixed-dim": "#ffafab",
        "surface-dim": "#0e0e0e",
        "inverse-surface": "#f9f9f9",
        "on-secondary-fixed-variant": "#a5001d",
        "on-surface-variant": "#ababab",
        "primary-dim": "#beee00",
        "on-tertiary-fixed-variant": "#006868",
        "inverse-on-surface": "#555555",
        "on-tertiary": "#006767",
        "on-primary-container": "#4a5e00",
        "on-secondary-fixed": "#700010",
        "on-error": "#450900",
        "error": "#ff7351",
        "tertiary-fixed": "#00ffff",
        "outline": "#757575",
        "surface-bright": "#2c2c2c",
        "on-secondary-container": "#fff6f5",
        "secondary-container": "#bf0024",
        "surface-container-lowest": "#000000",
        "secondary-fixed": "#ffc3c0",
        "tertiary-dim": "#00e6e6",
        "on-background": "#ffffff",
        "on-secondary": "#490007",
        "secondary": "#ff706f",
        "tertiary-container": "#00ffff",
        "on-primary-fixed-variant": "#526900",
        "primary": "#f3ffca",
        "tertiary": "#c1fffe",
        "on-primary": "#516700",
        "surface": "#0e0e0e",
        "error-dim": "#d53d18",
        "outline-variant": "#484848",
        "primary-fixed": "#cafd00",
        "on-surface": "#ffffff",
        "error-container": "#b92902",
        "surface-container-highest": "#262626",
        "surface-tint": "#f3ffca",
        "on-tertiary-container": "#005d5d",
        "tertiary-fixed-dim": "#00efef",
        "surface-container": "#191919",
        "primary-fixed-dim": "#beee00",
        "on-tertiary-fixed": "#004949",
        "surface-container-high": "#1f1f1f",
        "secondary-dim": "#e9002e"
      },
      "borderRadius": {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
