spring:
  application:
    name: CineVault

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/cinevault
    username: postgres
    password: Ninja#@3.14
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    access-secret: "Zl9a7Qp2w3XkGk6jQ8F0Fh5QbFzU9o4t3a6vZqP1WmE="
    refresh-secret: "Yp4rT2n9e8LqV6sJ3uXc5B7kM0hD1fWzR8tN4aC9sEo="
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000

  tmdb:
    api-key: 3b5b8da61073fa7055ba05490f27cc60
    base-url: https://api.themoviedb.org/3
    image-base: https://image.tmdb.org/t/p/w500

server:
  port: 5000